version: "1.0.0"
services:
  database:
    image: postgres
    container_name: postgres-for-order-service
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=root
    ports:
      - 5432:5432
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - 8001:8001
    container_name: my-order-service

