server:
  port: 8000

spring:
  application:
    name: user-service

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:1234}
    url: ${DB_URL:jdbc:mariadb://localhost:3306/kafka?characterEncoding=UTF-8&serverTimezone=UTC}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_URL:localhost:9092}
      group-id: sample-group-id-2

#docker run --name mariadb -p 3306:3306 -e MARIADB_ROOT_PASSWORD=1234 mariadb -d