server:
  port: 8000

spring:
  application:
    name: user-service

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mariadb://mariadb-for-user-service.backing-service.svc.cluster.local:3306/kafka?characterEncoding=UTF-8&serverTimezone=UTC

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  kafka:
    consumer:
      bootstrap-servers: kafka-0-internal.backing-service.svc.cluster.local:9092
      group-id: sample-group-id-2

#docker run --name mariadb -p 3306:3306 -e MARIADB_ROOT_PASSWORD=1234 mariadb -d