server:
  port: 8001

spring:
  application:
    name: order-service

  datasource:
    driver-class-name: org.postgresql.Driver
    username: root
    password: 1234
    url: jdbc:postgresql://localhost:5432/postgres

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true

  kafka:
    consumer:
      bootstrap-servers: localhost:29092
      group-id: sample-group-id-3
#docker run --name postgres -p 5432:5432 -e POSTGRES_PASSWORD=1234 -e POSTGRES_USER=root postgres