server:
  port: 8002

spring:
  application:
    name: product-service

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:1234}
    url: ${DB_URL:jdbc:mariadb://localhost:3306/kafka?characterEncoding=UTF-8&serverTimezone=UTC}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_URL:localhost:9092}
      group-id: sample-group-id-1


