server:
  port: 8002

spring:
  application:
    name: product-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://mysql-for-product-service.backing-service.svc.cluster.local/kafka?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  kafka:
    consumer:
      bootstrap-servers: localhost:29092
      group-id: sample-group-id-1


