server:
  port: 8002

spring:
  application:
    name: product-service

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mariadb://mariadb-for-product-service.backing-service.svc.cluster.local:3306/kafka?characterEncoding=UTF-8&serverTimezone=UTC

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  kafka:
    consumer:
      bootstrap-servers: kafka-0-internal.backing-service.svc.cluster.local:9092
      group-id: sample-group-id-1


